person = input("Who do you hate the most: ")
animal = input("Which animal is your favourite: ")
place = input("Your favourite place in the world: ")
print(" ********* ")
print(" ********* ")
print("Roses are red violets are blue")
print("The one you will marry is closest to you")
print("Their name is " + person)
print("And they'll eat your " + animal)
print("And then they'll take your heart\nAnd burn it down at " + place)